#server:
#  error:
#    include-message: always   # this makes your custom messages visible
#    include-binding-errors: always

server:
  shutdown: graceful

spring:
  application:
    name: InventoryBackend

  lifecycle:
    timeout-per-shutdown-phase: 45s   # ← How long Spring waits to finish active requests + close beans

  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate  # Validates the schema, makes sure it matches the entities
      #ddl-auto: update # Creates/updates tables automatically
      #ddl-auto: create-drop # Drops and rebuild the database schema on startup and shutdown (useful for testing)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Flyway configuration
  flyway:
    enabled: true
    # Estos permiten correr flyway sin hacer cambios a la base de datos
    #baseline-on-migrate: true   # uncomment only if you already have data in the DB
    #baseline-version: 3
    #baseline-description: "Schema created by JPA + manual data (V1+V2+V3 already applied)"

jwt:
  secret: superSecretKeyForInventoryApp2026MakeItAtLeast256BitsLongForHS512
  expiration-ms: 86400000   # 24 hours

app:
  upload:
    dir: /app/images